name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "## What was wrong"
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen
    validations:
      required: true
  - type: textarea
    id: code-that-caused
    attributes:
      label: Code that produced the error
      description: Formats to Python, no backticks needed
      render: python
    validations:
      required: false
  - type: textarea
    id: error-output
    attributes:
      label: Full error output
      description: Formats to shell, no backticks needed
      render: shell
    validations:
      required: false
  - type: markdown
    attributes:
      value: "## Potential Solutions"
  - type: textarea
    id: how-to-fix
    attributes:
      label: Fill this section in if you know how this could or should be fixed
      description: Include any relevant examples or reference material
    validations:
      required: false
  - type: input
    id: lib-version
    attributes:
      label: web3 Version
      description: Which version of web3 are you using?
      placeholder: x.x.x
    validations:
      required: false
  - type: input
    id: py-version
    attributes:
      label: Python Version
      description: Which version of Python are you using?
      placeholder: x.x.x
    validations:
      required: false
  - type: input
    id: os
    attributes:
      label: Operating System
      description: Which operating system are you using?
      placeholder: osx/linux/win
    validations:
      required: false
  - type: textarea
    id: pip-freeze
    attributes:
      label: Output from `pip freeze`
      description: Run `python -m pip freeze` and paste the output below
      render: shell
    validations:
      required: false
