name: Feature Request
description: Request a new feature
labels: ["feature_request"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: What feature should we add?
      description: Include any relevant examples or reference material
    validations:
      required: true
